# The default SRS config for the testbed

cu_cp:
  amf:
    addr: 192.168.101.14
    bind_addr: 0.0.0.0
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "99999"
            tai_slice_support_list:
              - sst: 1
                sd: 162
              - sst: 1
                sd: 163
              - sst: 1
                sd: 164
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
                sd: 162
              - sst: 1
                sd: 163
              - sst: 1
                sd: 164
  security:
    nia_pref_list: nia2,nia1
    nea_pref_list: nea2,nea1,nea3,nea0    # nea2 required for iPhone
  mobility:
    cells:
      - nr_cell_id: 0x66C000          # For the default gnb_id=411 (gnb_id_bit_length=22), NR cell IDs start with 0x66C000 and increment for each cell of the DU.
        periodic_report_cfg_id: 1     # This will configure a periodical report config for the serving cell.
    report_configs:                                        # Define report configs for cell 1
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024


cell_cfg:
  dl_arfcn: 630684
  common_scs: 30
  band: 78
  plmn: "00101"
  tac: 1
  pci: 1
  channel_bandwidth_MHz: 40
  ssb:
     ssb_block_power_dbm: -21
  nof_antennas_dl: 4
  nof_antennas_ul: 4
  # tdd_ul_dl_cfg:
  #   nof_dl_symbols: 5
  #   nof_dl_slots: 5
  #   nof_ul_slots: 4
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 7
    nof_dl_symbols: 6
    nof_ul_slots: 2
    nof_ul_symbols: 4
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 12
  pusch:
    mcs_table: qam256
  slicing:                              # Optional TEXT. Configure network slicing options. This can only be set via the configuration file.

    # Each slice has:
        # min_prb_policy_ratio → guaranteed floor (it always gets at least that much if it has traffic).
        # max_prb_policy_ratio → hard ceiling (it will never exceed that share).
        # priority → relative importance between slices.

    # When multiple slices want more than their guaranteed minimums:
        # The scheduler looks at their priority values.
        # Slices with higher priority get to “claim” additional PRBs before lower-priority slices.
        # If two slices have the same priority, they share equally (round-robin / proportional allocation, depending on the implementation).

        # Example - Suppose you have 100 PRBs available:

        #     Slice A: min = 20%, max = 60%, priority = 10
        #     Slice B: min = 20%, max = 80%, priority = 5

        # If both slices are active and demand more than their minimum:
        
        # 1. Each gets their min first → A = 20 PRBs, B = 20 PRBs.
        #     Remaining = 60 PRBs.

        # 2. The remaining 60 PRBs are allocated weighted by priority.
        #     Total weight = 10 + 5 = 15.
        #     A’s share = (10/15) × 60 = 40.
        #     B’s share = (5/15) × 60 = 20.

        # 3. Apply the max limits:
        #     A’s total = 20 + 40 = 60 (OK, matches its max).
        #     B’s total = 20 + 20 = 40 (well below its max of 80).


    -   # slice=internet                                  # Configure Slice 1
      sst: 1                                  # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
      sd: 162                                   # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 90               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
        priority: 1
    -  # slice=internet2                                         # Configure Slice 1
      sst: 1                                  # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
      sd: 163                                   # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 10               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
        priority: 1
    -  # slice=default                                     # Configure Slice 1
      sst: 1                                  # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
      sd: 164                                   # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 100               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
        priority: 1

cells:
  - pci: 1
    dl_arfcn: 630684

ru_ofh:
  ru_bandwidth_MHz: 40
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 429
  t1a_min_cp_ul: 285
  t1a_max_up: 196
  t1a_min_up: 50
  ta4_max: 75
  ta4_min: 0
  is_prach_cp_enabled: true
  ignore_ecpri_payload_size: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: none
  compr_bitwidth_prach: 16
  enable_ul_static_compr_hdr: false
  enable_dl_static_compr_hdr: false
  iq_scaling: 2.0
  cells:
  - network_interface: 0000:3f:00.5    # PCI address of the NIC card in your server
    ru_mac_addr: e2:53:8d:8f:a4:6b
    du_mac_addr: aa:bb:cc:11:22:33
    vlan_tag_up: 1
    vlan_tag_cp: 1
    prach_port_id: [4, 5, 6, 7]
    dl_port_id: [0, 1, 2, 3]
    ul_port_id: [0, 1, 2, 3]

# Will be added by the update script
#hal:
#   eal_args: "--lcores (0-1)@(1-30)"

log:
  filename: ./gnb.log
  ofh_level: warning
  all_level: warning
  gtpu_level: warning


metrics:
  autostart_stdout_metrics: true
