apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://altran5gran.azurecr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.ACRUsername .Values.image.ACRPassword (printf "%s:%s" .Values.image.ACRUsername .Values.image.ACRPassword | b64enc) | b64enc | quote }}
kind: Secret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: altran-acr-cred
type: kubernetes.io/dockerconfigjson
