apiVersion: v1
kind: ServiceAccount
metadata:
  name: srs-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: srs-role
rules:
- apiGroups: ["", "apps"]
  resources: ["endpoints", "pods", "configmaps"]
  verbs: ["get", "list", "patch", "update" ]
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["get", "list", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: srs-role-binding
subjects:
- kind: ServiceAccount
  name: srs-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: srs-role

# Allow the srs-service-account to access the sriov-device-plugin-config configmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-sriov-config
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
    resourceNames: ["sriov-device-plugin-config"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-sriov-config-binding
subjects:
  - kind: ServiceAccount
    name: srs-service-account
    namespace: ran
roleRef:
  kind: ClusterRole
  name: access-sriov-config
  apiGroup: rbac.authorization.k8s.io
