# yaml-language-server: $schema=../../tools/schemas/jrtc-ctl..schema.json
# Copyright (c) Microsoft Corporation. All rights reserved.

name: xran_packets_deployment
    
decoder:
  - type: decodergrpc
    port: 20789
      
app:
  - name: app1
    app: ${JRTC_PATH}/out/lib/libjrtc_pythonapp_loader.so
    app_params:
      - ${JRTC_APPS}/xran_packets/xran_packets
    port: 3001

jbpf:
  device:
    - id: 1
      port: 30450

  codelet_set:
    - device: 1
      config: ${JBPF_CODELETS}/xran_packets/xran_packets.yaml 
