codeletset_id: fapi_gnb_ul_config_stats

codelet_descriptor:

  - codelet_name: codelet1
    codelet_path: ${JBPF_CODELETS}/fapi_ul_conf/fapi_gnb_ul_config_stats_collect.o
    hook_name: fapi_ul_tti_request
    priority: 1

  - codelet_name: codelet2
    codelet_path: ${JBPF_CODELETS}/fapi_ul_conf/fapi_gnb_ul_config_stats_report.o
    hook_name: report_stats
    priority: 1
    out_io_channel:
      - name: output_map
        forward_destination: DestinationUDP
        serde:
          file_path: ${JBPF_CODELETS}/fapi_ul_conf/fapi_gnb_ul_config_stats:ul_config_stats_serializer.so
          protobuf:
            package_path: ${JBPF_CODELETS}/fapi_ul_conf/fapi_gnb_ul_config_stats.pb
            msg_name: ul_config_stats
    linked_maps:
      - map_name: stats_map
        linked_codelet_name: codelet1
        linked_map_name: stats_map
      - map_name: rnti_hash
        linked_codelet_name: codelet1
        linked_map_name: rnti_hash
      - map_name: not_empty
        linked_codelet_name: codelet1
        linked_map_name: not_empty